name: Python Scheduled Script

on: 
  schedule:
    - cron: "*/15 * * * *" #runs at 00:00 every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Timezone
        uses: szenius/set-timezone@v1.2
        with: 
          timezoneLinux: "Europe/Athens"
      - name: Checkout repository content
        uses: actions/checkout@v2
      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"
      - name: Execute Python script
        run: python pdf_to_txt.py
      - name: Commit files
        run:
          git config --local user.name ValiaDourou
          git config --local user.email "valiadourou@gmail.com"
          git add --all
          git commit -am "GH ACTION Headlines $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
